### ISSUE TITLE
Post install checklist

### ISSUE THREAD

**Issue by tyrsson** [axleus/axleus-core#18]
This draft issue is just for tracking the post install checklist of things that have to modified by tooling or by hand.

- [ ] Delegate at minimum the HomePageHandler
- [ ] Rename the home route to Home

Tooling considerations

- [ ] Make post install command smart enough to scan the RouteCollector or @settermjd route table tooling to detect how many handlers are routed and delegate them all in a config file.
